FROM node:20-alpine 
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build
RUN npm install -g serve

EXPOSE 80

CMD echo "window._env_ = { VITE_API_URL: \"$VITE_API_URL\" };" > /app/dist/env-config.js && serve -s dist -l 80